# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b40d51ca826256f7afead46f52bddf046f98f33f9736035ff0bfc6ffa369af0356b16f5c55e8d9a1da4143a439e8c70a7031653d96610bd78e6b3aa463a03ef7
  GITHUB_ID: <%= ENV["STATOCAT_GITHUB_ID"] %>
  GITHUB_SECRET: <%= ENV["STATOCAT_GITHUB_SECRET"] %>

test:
  secret_key_base: 4848d98a50a8ecd52ab215dce39cb61a92f9030df529d218229edce2aaffd98dade6c3d9daac695ca86b7722d555539425d84f859bd6d777e53a92495face763
  GITHUB_ID: <%= ENV["STATOCAT_GITHUB_ID"] %>
  GITHUB_SECRET: <%= ENV["STATOCAT_GITHUB_SECRET"] %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  GITHUB_ID: <%= ENV["STATOCAT_GITHUB_ID"] %>
  GITHUB_SECRET: <%= ENV["STATOCAT_GITHUB_SECRET"] %>
